name: Pull Request Notification

on:
  pull_request:
    types:
      - opened

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_PR }}
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "content": "<@1078050144869695578> someone made a pull request",
            "embeds": [
              {
                "title": "New Pull Request",
                "description": "${{ github.event.pull_request.title }}",
                "url": "${{ github.event.pull_request.html_url }}",
                "color": 3066993
              }
            ]
          }' $DISCORD_WEBHOOK
